services:
  - type: web
    name: fastapi-sdaas
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        value: your-secret-key-change-in-production
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: STORAGE_TYPE
        value: local
      - key: LOCAL_STORAGE_PATH
        value: ./storage
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: your-email@gmail.com
      - key: SMTP_PASSWORD
        value: your-app-password
      - key: DATABASE_URL
        fromDatabase:
          name: sdaas-mysql
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info

databases:
  - name: sdaas-mysql
    plan: free
    ipAllowList: []   # allows all connections
